// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: board_id.proto

package tickets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BoardId) Reset() {
	*x = BoardId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_board_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardId) ProtoMessage() {}

func (x *BoardId) ProtoReflect() protoreflect.Message {
	mi := &file_board_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardId.ProtoReflect.Descriptor instead.
func (*BoardId) Descriptor() ([]byte, []int) {
	return file_board_id_proto_rawDescGZIP(), []int{0}
}

func (x *BoardId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_board_id_proto protoreflect.FileDescriptor

var file_board_id_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x19, 0x0a, 0x07, 0x42, 0x6f, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x2d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_board_id_proto_rawDescOnce sync.Once
	file_board_id_proto_rawDescData = file_board_id_proto_rawDesc
)

func file_board_id_proto_rawDescGZIP() []byte {
	file_board_id_proto_rawDescOnce.Do(func() {
		file_board_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_board_id_proto_rawDescData)
	})
	return file_board_id_proto_rawDescData
}

var file_board_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_board_id_proto_goTypes = []any{
	(*BoardId)(nil), // 0: tickets.BoardId
}
var file_board_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_board_id_proto_init() }
func file_board_id_proto_init() {
	if File_board_id_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_board_id_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*BoardId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_board_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_board_id_proto_goTypes,
		DependencyIndexes: file_board_id_proto_depIdxs,
		MessageInfos:      file_board_id_proto_msgTypes,
	}.Build()
	File_board_id_proto = out.File
	file_board_id_proto_rawDesc = nil
	file_board_id_proto_goTypes = nil
	file_board_id_proto_depIdxs = nil
}
