// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: ticket_full_id.proto

package tickets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketFullId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Project *ProjectId `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Ticket  *TicketId  `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *TicketFullId) Reset() {
	*x = TicketFullId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_full_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketFullId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketFullId) ProtoMessage() {}

func (x *TicketFullId) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_full_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketFullId.ProtoReflect.Descriptor instead.
func (*TicketFullId) Descriptor() ([]byte, []int) {
	return file_ticket_full_id_proto_rawDescGZIP(), []int{0}
}

func (x *TicketFullId) GetProject() *ProjectId {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *TicketFullId) GetTicket() *TicketId {
	if x != nil {
		return x.Ticket
	}
	return nil
}

var File_ticket_full_id_proto protoreflect.FileDescriptor

var file_ticket_full_id_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x69, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a,
	0x10, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x67, 0x0a, 0x0c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x49, 0x64, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74,
	0x2d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_full_id_proto_rawDescOnce sync.Once
	file_ticket_full_id_proto_rawDescData = file_ticket_full_id_proto_rawDesc
)

func file_ticket_full_id_proto_rawDescGZIP() []byte {
	file_ticket_full_id_proto_rawDescOnce.Do(func() {
		file_ticket_full_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_full_id_proto_rawDescData)
	})
	return file_ticket_full_id_proto_rawDescData
}

var file_ticket_full_id_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ticket_full_id_proto_goTypes = []any{
	(*TicketFullId)(nil), // 0: tickets.TicketFullId
	(*ProjectId)(nil),    // 1: tickets.ProjectId
	(*TicketId)(nil),     // 2: tickets.TicketId
}
var file_ticket_full_id_proto_depIdxs = []int32{
	1, // 0: tickets.TicketFullId.project:type_name -> tickets.ProjectId
	2, // 1: tickets.TicketFullId.ticket:type_name -> tickets.TicketId
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ticket_full_id_proto_init() }
func file_ticket_full_id_proto_init() {
	if File_ticket_full_id_proto != nil {
		return
	}
	file_project_id_proto_init()
	file_ticket_id_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ticket_full_id_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TicketFullId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_full_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_full_id_proto_goTypes,
		DependencyIndexes: file_ticket_full_id_proto_depIdxs,
		MessageInfos:      file_ticket_full_id_proto_msgTypes,
	}.Build()
	File_ticket_full_id_proto = out.File
	file_ticket_full_id_proto_rawDesc = nil
	file_ticket_full_id_proto_goTypes = nil
	file_ticket_full_id_proto_depIdxs = nil
}
