// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: ticket_short.proto

package tickets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *TicketFullId `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Title      *string       `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Status     *string       `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	AssignedTo []*UserShort  `protobuf:"bytes,4,rep,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
}

func (x *TicketShort) Reset() {
	*x = TicketShort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_short_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketShort) ProtoMessage() {}

func (x *TicketShort) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_short_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketShort.ProtoReflect.Descriptor instead.
func (*TicketShort) Descriptor() ([]byte, []int) {
	return file_ticket_short_proto_rawDescGZIP(), []int{0}
}

func (x *TicketShort) GetId() *TicketFullId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TicketShort) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *TicketShort) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *TicketShort) GetAssignedTo() []*UserShort {
	if x != nil {
		return x.AssignedTo
	}
	return nil
}

var File_ticket_short_proto protoreflect.FileDescriptor

var file_ticket_short_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x1a, 0x14, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x01, 0x0a, 0x0b, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x2a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x49, 0x64, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x88, 0x01, 0x01, 0x12, 0x33, 0x0a, 0x0b, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x6f, 0x42, 0x05,
	0x0a, 0x03, 0x5f, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x2d,
	0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_short_proto_rawDescOnce sync.Once
	file_ticket_short_proto_rawDescData = file_ticket_short_proto_rawDesc
)

func file_ticket_short_proto_rawDescGZIP() []byte {
	file_ticket_short_proto_rawDescOnce.Do(func() {
		file_ticket_short_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_short_proto_rawDescData)
	})
	return file_ticket_short_proto_rawDescData
}

var file_ticket_short_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ticket_short_proto_goTypes = []any{
	(*TicketShort)(nil),  // 0: tickets.TicketShort
	(*TicketFullId)(nil), // 1: tickets.TicketFullId
	(*UserShort)(nil),    // 2: tickets.UserShort
}
var file_ticket_short_proto_depIdxs = []int32{
	1, // 0: tickets.TicketShort.id:type_name -> tickets.TicketFullId
	2, // 1: tickets.TicketShort.assigned_to:type_name -> tickets.UserShort
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ticket_short_proto_init() }
func file_ticket_short_proto_init() {
	if File_ticket_short_proto != nil {
		return
	}
	file_ticket_full_id_proto_init()
	file_user_short_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ticket_short_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TicketShort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ticket_short_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_short_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_short_proto_goTypes,
		DependencyIndexes: file_ticket_short_proto_depIdxs,
		MessageInfos:      file_ticket_short_proto_msgTypes,
	}.Build()
	File_ticket_short_proto = out.File
	file_ticket_short_proto_rawDesc = nil
	file_ticket_short_proto_goTypes = nil
	file_ticket_short_proto_depIdxs = nil
}
