// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: board_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BoardService_GetAll_FullMethodName        = "/proto.BoardService/GetAll"
	BoardService_GetAllUpdates_FullMethodName = "/proto.BoardService/GetAllUpdates"
	BoardService_Get_FullMethodName           = "/proto.BoardService/Get"
	BoardService_GetUpdates_FullMethodName    = "/proto.BoardService/GetUpdates"
	BoardService_Create_FullMethodName        = "/proto.BoardService/Create"
)

// BoardServiceClient is the client API for BoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BoardServiceClient interface {
	GetAll(ctx context.Context, in *BoardFullId, opts ...grpc.CallOption) (*Board, error)
	GetAllUpdates(ctx context.Context, in *BoardFullId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TicketShort], error)
	Get(ctx context.Context, in *BoardFilter, opts ...grpc.CallOption) (*Board, error)
	GetUpdates(ctx context.Context, in *BoardFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TicketShort], error)
	Create(ctx context.Context, in *Board, opts ...grpc.CallOption) (*BoardFullId, error)
}

type boardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBoardServiceClient(cc grpc.ClientConnInterface) BoardServiceClient {
	return &boardServiceClient{cc}
}

func (c *boardServiceClient) GetAll(ctx context.Context, in *BoardFullId, opts ...grpc.CallOption) (*Board, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Board)
	err := c.cc.Invoke(ctx, BoardService_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) GetAllUpdates(ctx context.Context, in *BoardFullId, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TicketShort], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoardService_ServiceDesc.Streams[0], BoardService_GetAllUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BoardFullId, TicketShort]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoardService_GetAllUpdatesClient = grpc.ServerStreamingClient[TicketShort]

func (c *boardServiceClient) Get(ctx context.Context, in *BoardFilter, opts ...grpc.CallOption) (*Board, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Board)
	err := c.cc.Invoke(ctx, BoardService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boardServiceClient) GetUpdates(ctx context.Context, in *BoardFilter, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TicketShort], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BoardService_ServiceDesc.Streams[1], BoardService_GetUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BoardFilter, TicketShort]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoardService_GetUpdatesClient = grpc.ServerStreamingClient[TicketShort]

func (c *boardServiceClient) Create(ctx context.Context, in *Board, opts ...grpc.CallOption) (*BoardFullId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoardFullId)
	err := c.cc.Invoke(ctx, BoardService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BoardServiceServer is the server API for BoardService service.
// All implementations must embed UnimplementedBoardServiceServer
// for forward compatibility.
type BoardServiceServer interface {
	GetAll(context.Context, *BoardFullId) (*Board, error)
	GetAllUpdates(*BoardFullId, grpc.ServerStreamingServer[TicketShort]) error
	Get(context.Context, *BoardFilter) (*Board, error)
	GetUpdates(*BoardFilter, grpc.ServerStreamingServer[TicketShort]) error
	Create(context.Context, *Board) (*BoardFullId, error)
	mustEmbedUnimplementedBoardServiceServer()
}

// UnimplementedBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBoardServiceServer struct{}

func (UnimplementedBoardServiceServer) GetAll(context.Context, *BoardFullId) (*Board, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBoardServiceServer) GetAllUpdates(*BoardFullId, grpc.ServerStreamingServer[TicketShort]) error {
	return status.Errorf(codes.Unimplemented, "method GetAllUpdates not implemented")
}
func (UnimplementedBoardServiceServer) Get(context.Context, *BoardFilter) (*Board, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBoardServiceServer) GetUpdates(*BoardFilter, grpc.ServerStreamingServer[TicketShort]) error {
	return status.Errorf(codes.Unimplemented, "method GetUpdates not implemented")
}
func (UnimplementedBoardServiceServer) Create(context.Context, *Board) (*BoardFullId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBoardServiceServer) mustEmbedUnimplementedBoardServiceServer() {}
func (UnimplementedBoardServiceServer) testEmbeddedByValue()                      {}

// UnsafeBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BoardServiceServer will
// result in compilation errors.
type UnsafeBoardServiceServer interface {
	mustEmbedUnimplementedBoardServiceServer()
}

func RegisterBoardServiceServer(s grpc.ServiceRegistrar, srv BoardServiceServer) {
	// If the following call pancis, it indicates UnimplementedBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BoardService_ServiceDesc, srv)
}

func _BoardService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardFullId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).GetAll(ctx, req.(*BoardFullId))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_GetAllUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BoardFullId)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoardServiceServer).GetAllUpdates(m, &grpc.GenericServerStream[BoardFullId, TicketShort]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoardService_GetAllUpdatesServer = grpc.ServerStreamingServer[TicketShort]

func _BoardService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BoardFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Get(ctx, req.(*BoardFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BoardService_GetUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BoardFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoardServiceServer).GetUpdates(m, &grpc.GenericServerStream[BoardFilter, TicketShort]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BoardService_GetUpdatesServer = grpc.ServerStreamingServer[TicketShort]

func _BoardService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Board)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoardServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BoardService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoardServiceServer).Create(ctx, req.(*Board))
	}
	return interceptor(ctx, in, info, handler)
}

// BoardService_ServiceDesc is the grpc.ServiceDesc for BoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BoardService",
	HandlerType: (*BoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAll",
			Handler:    _BoardService_GetAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BoardService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BoardService_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllUpdates",
			Handler:       _BoardService_GetAllUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUpdates",
			Handler:       _BoardService_GetUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "board_service.proto",
}
