// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: ticket_link_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketLinkType int32

const (
	TicketLinkType_TLT_RELATED    TicketLinkType = 0
	TicketLinkType_TLT_DUPLICATE  TicketLinkType = 1
	TicketLinkType_TLT_PARENT     TicketLinkType = 2
	TicketLinkType_TLT_CHILD      TicketLinkType = 3
	TicketLinkType_TLT_BLOCKS     TicketLinkType = 4
	TicketLinkType_TLT_DEPENDS_ON TicketLinkType = 5
)

// Enum value maps for TicketLinkType.
var (
	TicketLinkType_name = map[int32]string{
		0: "TLT_RELATED",
		1: "TLT_DUPLICATE",
		2: "TLT_PARENT",
		3: "TLT_CHILD",
		4: "TLT_BLOCKS",
		5: "TLT_DEPENDS_ON",
	}
	TicketLinkType_value = map[string]int32{
		"TLT_RELATED":    0,
		"TLT_DUPLICATE":  1,
		"TLT_PARENT":     2,
		"TLT_CHILD":      3,
		"TLT_BLOCKS":     4,
		"TLT_DEPENDS_ON": 5,
	}
)

func (x TicketLinkType) Enum() *TicketLinkType {
	p := new(TicketLinkType)
	*p = x
	return p
}

func (x TicketLinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketLinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_ticket_link_type_proto_enumTypes[0].Descriptor()
}

func (TicketLinkType) Type() protoreflect.EnumType {
	return &file_ticket_link_type_proto_enumTypes[0]
}

func (x TicketLinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketLinkType.Descriptor instead.
func (TicketLinkType) EnumDescriptor() ([]byte, []int) {
	return file_ticket_link_type_proto_rawDescGZIP(), []int{0}
}

var File_ticket_link_type_proto protoreflect.FileDescriptor

var file_ticket_link_type_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a,
	0x77, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x4c, 0x54, 0x5f, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x4c, 0x54, 0x5f, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43,
	0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x4c, 0x54, 0x5f, 0x50, 0x41, 0x52,
	0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x4c, 0x54, 0x5f, 0x43, 0x48, 0x49,
	0x4c, 0x44, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x4c, 0x54, 0x5f, 0x42, 0x4c, 0x4f, 0x43,
	0x4b, 0x53, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x4c, 0x54, 0x5f, 0x44, 0x45, 0x50, 0x45,
	0x4e, 0x44, 0x53, 0x5f, 0x4f, 0x4e, 0x10, 0x05, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x2d, 0x6f, 0x62,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_link_type_proto_rawDescOnce sync.Once
	file_ticket_link_type_proto_rawDescData = file_ticket_link_type_proto_rawDesc
)

func file_ticket_link_type_proto_rawDescGZIP() []byte {
	file_ticket_link_type_proto_rawDescOnce.Do(func() {
		file_ticket_link_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_link_type_proto_rawDescData)
	})
	return file_ticket_link_type_proto_rawDescData
}

var file_ticket_link_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ticket_link_type_proto_goTypes = []any{
	(TicketLinkType)(0), // 0: proto.TicketLinkType
}
var file_ticket_link_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ticket_link_type_proto_init() }
func file_ticket_link_type_proto_init() {
	if File_ticket_link_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_link_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ticket_link_type_proto_goTypes,
		DependencyIndexes: file_ticket_link_type_proto_depIdxs,
		EnumInfos:         file_ticket_link_type_proto_enumTypes,
	}.Build()
	File_ticket_link_type_proto = out.File
	file_ticket_link_type_proto_rawDesc = nil
	file_ticket_link_type_proto_goTypes = nil
	file_ticket_link_type_proto_depIdxs = nil
}
