// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: user_short.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             *UserId   `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Username       *string   `protobuf:"bytes,2,opt,name=username,proto3,oneof" json:"username,omitempty"`
	ProfilePicture *FileInfo `protobuf:"bytes,3,opt,name=profile_picture,json=profilePicture,proto3,oneof" json:"profile_picture,omitempty"`
}

func (x *UserShort) Reset() {
	*x = UserShort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_short_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserShort) ProtoMessage() {}

func (x *UserShort) ProtoReflect() protoreflect.Message {
	mi := &file_user_short_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserShort.ProtoReflect.Descriptor instead.
func (*UserShort) Descriptor() ([]byte, []int) {
	return file_user_short_proto_rawDescGZIP(), []int{0}
}

func (x *UserShort) GetId() *UserId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UserShort) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserShort) GetProfilePicture() *FileInfo {
	if x != nil {
		return x.ProfilePicture
	}
	return nil
}

var File_user_short_proto protoreflect.FileDescriptor

var file_user_short_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x22, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x3d, 0x0a, 0x0f,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x02, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f,
	0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x42,
	0x12, 0x0a, 0x10, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x73, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x2d, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_short_proto_rawDescOnce sync.Once
	file_user_short_proto_rawDescData = file_user_short_proto_rawDesc
)

func file_user_short_proto_rawDescGZIP() []byte {
	file_user_short_proto_rawDescOnce.Do(func() {
		file_user_short_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_short_proto_rawDescData)
	})
	return file_user_short_proto_rawDescData
}

var file_user_short_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_short_proto_goTypes = []any{
	(*UserShort)(nil), // 0: proto.UserShort
	(*UserId)(nil),    // 1: proto.UserId
	(*FileInfo)(nil),  // 2: proto.FileInfo
}
var file_user_short_proto_depIdxs = []int32{
	1, // 0: proto.UserShort.id:type_name -> proto.UserId
	2, // 1: proto.UserShort.profile_picture:type_name -> proto.FileInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_short_proto_init() }
func file_user_short_proto_init() {
	if File_user_short_proto != nil {
		return
	}
	file_file_info_proto_init()
	file_user_id_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_short_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserShort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_user_short_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_short_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_short_proto_goTypes,
		DependencyIndexes: file_user_short_proto_depIdxs,
		MessageInfos:      file_user_short_proto_msgTypes,
	}.Build()
	File_user_short_proto = out.File
	file_user_short_proto_rawDesc = nil
	file_user_short_proto_goTypes = nil
	file_user_short_proto_depIdxs = nil
}
